### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [matthewmorek/matthewmorek.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by matthewmorek** [comment]
Thanks for reaching out, but this is just a fork of @subnixr's minimal theme with a few bits customized, and I've added it as a test repo to see how pulling themes via antigen would work for my personal needs.
